version: '3'

services:
    mongo:
        image: mongo:latest
        restart: always
        volumes:
            - mongo_volume:/data/db
        ports:
            - 27017:27017

    node:
        build: .
        ports:
            - 4000:4000
        environment:
            - PORT=4000
            - CONNECTION_STRING=mongodb://mongo:27017/my_db_name
            - NODE_ENV=development
            - JWT_SECRET=ThisIsASecret
        depends_on:
            - mongo

volumes:
    mongo_volume: {}